### PR TITLE
Python3, y-Axis label + unit, plot size

### PR DESCRIPTION
**Pull request by O2-AC**
This version works with Python3 and gives new arguments to the plot() function to control the y-Axis Label. It also defines a new set_size() function, in order to scale the plot area.

### CODE REVIEW

**Review by giacomomarchioro — COMMENTED** [review]
Thanks,Seems a good idea, probably is better to call it `figsize` so the user may understand that it refers to that parameter of matplotlib. I don't think that 'FATAL ERROR in size selection!' will never occur because you already passed a conditional statement before.We could set it by defaul to `None` instead of `auto`  and pass `self.size` or better `self.figsize` like this `fig = plt.figure(figsize=self.figsize)` I have to check if it works if so the if-else statement in line 237-240 can be avoided.

**Comment by O2-AC** [comment]
Good idea, renaming the function altogether. I will redo this as soon as possible and add it to the pull request, stay tuned. 

To be fair this was a quick an dirty method that for a chang worked without producing any errors ;)

**Comment by giacomomarchioro** [comment]
I've missed the `ylabel` suggestion.  I think it's an interesting feature but maybe it's a little bit an over complication, because the user need to read and rememebr the code and it could confuse a little bit these two parameters, unit and label. What if we put a simple `ylabel` and set it to default to `Energies [kcal/mol]` the extra-characters to type in this solution are very few. I would like to keep it as simple as possible and according to matplotlib standard. Thanks for your help and suggestions!

**Comment by O2-AC** [comment]
The default for `ylabel` is set to `Energies [kcal/mol]`. Only if you want to change this you can do it individually for the Label and unit.  I added this, since I often vary between `[kcal/mol]` and `[kJ/mol]` its quite convenient to have the switch there in case. The solution is fully backwards compatible.

Regarding the `figsize`: The function call was changed to `figsize()`, the internal argument however had to be called different from that. So under the hood I refer to size as `self.size` which is set to `None` initially, therefore using the matplotlib standard settings.

**Comment by giacomomarchioro** [comment]
Ok, mayvbe we could use `set_figsize` as function name, and keep `figsize` this would make things clear since size may refer to many things, even though usually you can set it apriori using `plt.rcParams["figure.figsize"] = (20,3)`  I'll test the different options. Thanks for your interest in the project!

**Comment by giacomomarchioro** [comment]
I've integrated the ylabel suggestion simplifying it a little bit, I think there is no need to split it into two arguments. Regarding the figsize, I think it is better to use matplotlib directly. Thanks a lot for your suggestions. I credit you on the contributions.

**Pull request closed without merging**
